### ISSUE TITLE
在多次proc kill后系统挂起

### ISSUE THREAD

**Issue by 000999888111** [plos-clan/CoolPotOS#13]
在按顺序kill ctu，ck，shell后系统挂起，正常来说此时应该出现错误屏幕，但是并没有。
并且此后的热重启会卡住，无法正常启动shell

**Comment by 000999888111** [comment]
热重启卡在memory manager处

**Comment by 000999888111** [comment]
测试只需要kill ck和shell，ctu是不必要的，并且可以稳定复现

**Comment by 000999888111** [comment]
![image](https://github.com/user-attachments/assets/be7daa2e-cb49-4b86-ac13-1e554f163ced)
第一次重启（VM的reboot）
![image](https://github.com/user-attachments/assets/a7e5f868-ab05-493b-ade0-daf83ef2c49f)
第二次重启，随后重启不会再变化
（我总感觉应该把这两个分成两个issue，因为正常使用也会造成重启异常）

**Comment by xiaoyi1212** [comment]
重构后的代码已递交回该存储库，感谢您的支持
