### ISSUE TITLE
在根目录下异常操作导致崩溃

### ISSUE THREAD

**Issue by 000999888111** [plos-clan/CoolPotOS#15]
![image](https://github.com/user-attachments/assets/efc2f2e7-d487-4c74-bb51-c9d335c65ff3)

在disk cg A后cd ..或sysinfo会导致崩溃
复现不稳定，可能需要多试几次
话说除了那个内核错误就没有别的错误屏幕了吗（恼）

**Comment by xiaoyi1212** [comment]
啊旧版 VFS系统问题， CoolPotOS 目前停更状态

**Comment by xiaoyi1212** [comment]
https://github.com/Mdr-C-Tutorial/MdrOS
你可以上这个存储库，然后进GitHub Actions下载构建好的ISO镜像 :D

**Comment by xiaoyi1212** [comment]
重构后的代码已递交回该存储库，感谢您的支持
